// Generated by CoffeeScript 1.8.0
(function() {
  var app, express, http, path, server;

  express = require('express');

  path = require("path");

  http = require('http');

  app = express();

  server = http.createServer(app);

  app.use(express["static"](path.join("" + __dirname + "/css")));

  app.use(express["static"](path.join("" + __dirname + "/script/js")));

  app.get('/', function(req, res) {
    return res.sendFile("" + __dirname + "/index.html");
  });

  app.listen(3000);

}).call(this);
