// Generated by CoffeeScript 1.8.0
(function() {
  var canvas, mousePos, textLocation;

  mousePos = function(evt) {
    var box;
    box = document.getElementById("board").getBoundingClientRect();
    return [evt.clientX - box.left, -1 * (evt.clientY - box.right)];
  };

  canvas = $(function() {
    return $("#board");
  });

  textLocation = $(function() {
    return $("#pos");
  });

  document.getElementById("board").addEventListener("mousemove", function(evt) {
    return console.log("" + (mousePos(evt)[0]) + " " + (mousePos(evt)[1]));
  });

}).call(this);
