// Generated by CoffeeScript 1.8.0
(function() {
  var box, canvas, context, height, i, imageData, mousePos, width, _i, _ref;

  canvas = document.getElementById("board");

  box = canvas.getBoundingClientRect();

  width = canvas.width;

  height = canvas.height;

  context = canvas.getContext("2d");

  mousePos = function(evt) {
    return [evt.clientX - box.left, -1 * (evt.clientY - box.right)];
  };

  imageData = context.createImageData(width, height);

  for (i = _i = 0, _ref = imageData.data.length; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
    imageData.data[i] = Math.floor(Math.random() * 120);
  }

  context.putImageData(imageData, 0, 0);

  document.getElementById("board").addEventListener("mousemove", function(evt) {
    var _j, _ref1;
    for (i = _j = 0, _ref1 = imageData.data.length; 0 <= _ref1 ? _j <= _ref1 : _j >= _ref1; i = 0 <= _ref1 ? ++_j : --_j) {
      imageData.data[i] = 255;
      if (i % 4 !== 3) {
        imageData.data[i] = Math.floor(Math.random() * 120);
      }
    }
    return context.putImageData(imageData, 0, 0);
  });

}).call(this);
